In [1]:
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)

Python version
3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)


In [2]:
import tensorflow as tf
from scipy.linalg import logm, expm
import numpy as np
import time
import math

In [3]:
SQRT_2 = tf.sqrt(tf.constant(2.,dtype=tf.float64))

def norminv(x):
    return SQRT_2*tf.math.erfinv(2*(x-0.5))

In [4]:
P = np.array([[0.8, 0.1, 0.1],[0.1,0.8,0.1],[0.,0.,1.]])
P

array([[0.8, 0.1, 0.1],
       [0.1, 0.8, 0.1],
       [0. , 0. , 1. ]])

In [6]:
L = logm(P)
L

array([[-0.23101773,  0.12565721,  0.10536052],
       [ 0.12565721, -0.23101773,  0.10536052],
       [ 0.        ,  0.        ,  0.        ]])

In [7]:
def P_t(L,t):
    return expm(L*t)

In [8]:
P_t(L,2.)

array([[0.65, 0.16, 0.19],
       [0.16, 0.65, 0.19],
       [0.  , 0.  , 1.  ]])

In [9]:
P*P

array([[0.64, 0.01, 0.01],
       [0.01, 0.64, 0.01],
       [0.  , 0.  , 1.  ]])

In [10]:
np.matmul(P,P)

array([[0.65, 0.16, 0.19],
       [0.16, 0.65, 0.19],
       [0.  , 0.  , 1.  ]])

In [12]:
pt = P_t(L,0.5)
pt

array([[0.89267166, 0.05601164, 0.0513167 ],
       [0.05601164, 0.89267166, 0.0513167 ],
       [0.        , 0.        , 1.        ]])

In [21]:
v = pt[:,1]*pt[1,:]/P[1,1]
v

array([0.00392163, 0.99607837, 0.        ])

In [35]:
np.outer(pt,pt).reshape(-1,3)

array([[0.7968627 , 0.05      , 0.04580897],
       [0.05      , 0.7968627 , 0.04580897],
       [0.        , 0.        , 0.89267166],
       [0.05      , 0.0031373 , 0.00287433],
       [0.0031373 , 0.05      , 0.00287433],
       [0.        , 0.        , 0.05601164],
       [0.04580897, 0.00287433, 0.0026334 ],
       [0.00287433, 0.04580897, 0.0026334 ],
       [0.        , 0.        , 0.0513167 ],
       [0.05      , 0.0031373 , 0.00287433],
       [0.0031373 , 0.05      , 0.00287433],
       [0.        , 0.        , 0.05601164],
       [0.7968627 , 0.05      , 0.04580897],
       [0.05      , 0.7968627 , 0.04580897],
       [0.        , 0.        , 0.89267166],
       [0.04580897, 0.00287433, 0.0026334 ],
       [0.00287433, 0.04580897, 0.0026334 ],
       [0.        , 0.        , 0.0513167 ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.

In [46]:
def f(x,y):
    print(x,y)
    return np.array(x*y)

In [50]:
np.multiply.outer(pt,pt.T)

array([[[[0.7968627 , 0.05      , 0.        ],
         [0.05      , 0.7968627 , 0.        ],
         [0.04580897, 0.04580897, 0.89267166]],

        [[0.05      , 0.0031373 , 0.        ],
         [0.0031373 , 0.05      , 0.        ],
         [0.00287433, 0.00287433, 0.05601164]],

        [[0.04580897, 0.00287433, 0.        ],
         [0.00287433, 0.04580897, 0.        ],
         [0.0026334 , 0.0026334 , 0.0513167 ]]],


       [[[0.05      , 0.0031373 , 0.        ],
         [0.0031373 , 0.05      , 0.        ],
         [0.00287433, 0.00287433, 0.05601164]],

        [[0.7968627 , 0.05      , 0.        ],
         [0.05      , 0.7968627 , 0.        ],
         [0.04580897, 0.04580897, 0.89267166]],

        [[0.04580897, 0.00287433, 0.        ],
         [0.00287433, 0.04580897, 0.        ],
         [0.0026334 , 0.0026334 , 0.0513167 ]]],


       [[[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        

In [54]:
np.multiply(pt[0],pt.T[0])

array([0.7968627, 0.0031373, 0.       ])

In [69]:
r = np.zeros((3,3,3))

In [86]:
for i in range(len(pt)):
    for j in range(len(pt)):
        r[i,j] = np.multiply(pt[i], pt.T[j])/P[i,j]
r

array([[[0.99607837, 0.00392163, 0.        ],
        [0.5       , 0.5       , 0.        ],
        [0.45808966, 0.02874332, 0.51316702]],

       [[0.5       , 0.5       , 0.        ],
        [0.00392163, 0.99607837, 0.        ],
        [0.02874332, 0.45808966, 0.51316702]],

       [[       nan,        nan,        nan],
        [       nan,        nan,        nan],
        [0.        , 0.        , 1.        ]]])

In [77]:
r = np.einsum('ik,kj->ijk',pt,pt)

In [78]:
r[0,0]

array([0.7968627, 0.0031373, 0.       ])

In [84]:
P

array([[0.8, 0.1, 0.1],
       [0.1, 0.8, 0.1],
       [0. , 0. , 1. ]])

In [83]:
r/P

array([[[0.99607837, 0.03137303, 0.        ],
        [0.5       , 0.0625    , 0.        ],
        [       inf,        inf, 0.0513167 ]],

       [[0.0625    , 0.5       , 0.        ],
        [0.03137303, 0.99607837, 0.        ],
        [       inf,        inf, 0.0513167 ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [       nan,        nan, 1.        ]]])

In [ ]:
a = ['A', 'B']
b = ['A', 'C']

